version: 2

updates:
  - package-ecosystem: 'gitsubmodule'
    directory: '/'
    schedule:
      interval: 'daily'
    # reduce load in periods of high commit volume.
    open-pull-requests-limit: 2

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
