version: 2

updates:
  - package-ecosystem: 'gitsubmodule'
    directory: '/'
    schedule:
      interval: 'daily'
      time: "08:00"

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
