dist: bionic
language: shell
os: linux

notifications:
  email:
    - tchajed@mit.edu
    - joseph.tassarotti@bc.edu

branches:
  only:
    - master
    # for version tags of the form v0.1 or v0.1.1
    - /^v\d+\.\d+(\.\d+)?$/
    - /^ci\//
    - deep

cache:
  directories:
    - $HOME/.stack

services:
  - docker

jobs:
  include:
    - env: COQ_VERSION="dev"
    - env: COQ_VERSION="8.10"
    - env: COQ_VERSION="8.9"
    - env: COQ_VERSION="dev" UPDATE_DEPS=true
  allow_failures:
    - env: COQ_VERSION="dev" UPDATE_DEPS=true

# On Travis cloning the gitlab dependencies fails due to a certificate error. In
# order to disable SSL verification for the submodule init, we have to tell
# Travis not to initialize submodules.
git:
  submodules: false

before_install:
  - git -c http.sslVerify=false submodule update --init --recursive
  - |
    if [ "${UPDATE_DEPS}" = "true" ]; then
      git -c http.sslVerify=false submodule update --init --remote
    fi
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install: |
  # Prepare the COQ container
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/demo -w /home/coq/demo "coqorg/coq:${COQ_VERSION}"
  docker exec COQ /bin/bash --login -c "
    # This bash script is double-quoted to interpolate Travis CI env vars:
    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex  # -e = exit on failure; -x = trace for debug
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip sqlite3
    pip3 install -r etc/requirements.txt -r etc/requirements-test.txt
    #opam update -y
    opam switch \${COMPILER_EDGE}; eval \$(opam env)
    opam config list
    opam repo list
    opam list
    echo \"git log: https://github.com/coq/coq/commits/\$(opam info -f source-hash coq)\"
    "
before_script:
  - |
    docker exec COQ /bin/bash --login -c "
      export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
      sudo chown -R coq:coq /home/coq/demo
      "
  - source ./etc/ci/travis_keep_alive.sh

script:
  - echo -e "${ANSI_YELLOW}Building ${TRAVIS_REPO_SLUG}...${ANSI_RESET}" && echo -en 'travis_fold:start:build\\r'
  - |
    docker exec COQ /bin/bash --login -c "
      export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
      export LC_ALL=C.UTF-8
      set -ex
      ~/.local/bin/pytest etc
      make -j2 -k ci
      chmod -R a+rw replicated-disk
      "
  - cd replicated-disk
  - stack --allow-different-user test
  - echo -en 'travis_fold:end:build\\r'

after_script:
  - docker stop COQ

after_success:
  - kill $PID_KEEP_ALIVE
