name: replicated-disk
version: 0.1.0.0
github: "mit-pdos/armada"
license: MIT
author: "Armada authors"
maintainer: "tchajed@mit.edu"
copyright: "2019 Armada authors"

description: Please see the Armada README on GitHub at <https://github.com/mit-pdos/armada>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - mtl
  - unix
  - unix-bytestring
  - directory
  - binary

library:
  source-dirs:
    - src
    - extract

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: replicated-disk
