name:                database
version:             0.1.0.0
github:              "mit-pdos/argosy"
license:             BSD3
author:              "Argosy authors"
copyright:           "2019 Argosy authors"

extra-source-files:
- README.md
- fiximports.py

description:         Please see the Argosy README

dependencies:
- base >= 4.7 && < 5
- bytestring
- mtl
- forkable-monad
- unix
- unix-bytestring
- dynamic-mvector
- hashtables
- hashable
- directory
- filepath
- concurrent-extra

ghc-options:
  - -O2

library:
  source-dirs: src

executables:
  extraction-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - database
    - criterion
    - deepseq

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: database
