name:                logging-client
version:             0.1.0.0
license:             BSD3
author:              "Argosy authors"
copyright:           "2018 Argosy authors"

description:         Please see the Argosy README

dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- directory
- mtl
- optparse-applicative
- unix
- unix-bytestring

library:
  source-dirs:
    - src
    - extract

executables:
  logging-cli:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - logging-client
    ghc-options:
      - -threaded
      - -rtsopts

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: logging-client
