translate = [
  "HardState",
  "Entry",
  "ConfState",
  "ConfChange",
  "ConfChangeType",
  "ConfChangeAddNode",
  "EntryConfChange",
  "Snapshot",
  "EntryType",
  "SnapshotMetadata",
]
axiomatize = []
