name: CI

# Controls when the action will run:
# https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#filtering-for-specific-branches-tags-and-paths
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - dev
          - '8.12'
      max-parallel: 4
      # don't cancel all in-progress jobs if one matrix job fails:
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: coq-community/docker-coq-action@v1
      with:
        opam_file: 'coq-perennial.opam'
        coq_version: ${{ matrix.coq_version }}
        ocaml_version: '4.09-flambda'
        install: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip sqlite3
          pip3 install -r etc/requirements.txt -r etc/requirements-test.txt
        before_script: |
          sudo chown -R coq:coq . # workaround a permission issue
        script: |
          make -j2 -k ci
        after_script: |
          ./etc/timing-report.py --max-files 30 > timing.txt
          cat timing.txt
        uninstall: ""
    - name: Revert permissions
      # to avoid a warning at cleanup time
      if: ${{ always() }}
      run: sudo chown -R 1001:116 .
    - uses: actions/upload-artifact@v2
      with:
        name: timing-report
        path: timing.txt
