name: CI

# Controls when the action will run:
# https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#filtering-for-specific-branches-tags-and-paths
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        coq_version:
          - dev
          - '8.12'
      max-parallel: 4
      # don't cancel all in-progress jobs if one matrix job fails:
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: coq-community/docker-coq-action@v1
      with:
        opam_file: 'coq-perennial.opam'
        coq_version: ${{ matrix.coq_version }}
        ocaml_version: '4.09-flambda'
        custom_script: |
          startGroup Install dependencies
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip sqlite3
            pip3 install -r etc/requirements.txt -r etc/requirements-test.txt
          endGroup
          startGroup Print opam config
            opam config list; opam repo list; opam list
          endGroup
          startGroup Build
            make -j2 -k ci
          endGroup
