name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: merge
        # a separate repo-wide ruleset ensures that dependabot PRs only merge
        # after CI passes.
        run: gh pr merge --auto --merge --delete-branch "$PR_URL"
