name: CI (updated dependencies)

on:
  schedule:
    # every day at 8am UTC (3am EST)
    - cron: "0 8 * * *"

jobs:
  build:
    name: "update dependencies (dev)"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: "Update dependencies"
        run: |
          git submodule update --remote
      - uses: coq-community/docker-coq-action@v1
        with:
          coq_version: dev
          ocaml_version: "4.13-flambda"
          install: |
            startGroup Install dependencies
              sudo apt-get update
              sudo apt-get install -y python3 python3-pip sqlite3
              pip3 install -r etc/requirements.txt
            endGroup
          before_script: |
            sudo chown -R coq:coq .
          script: |
            startGroup Build
              make -j2 -k ci
            endGroup
          uninstall: |
            make clean
      - name: Revert permissions
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .
